name: pipe-lab

on:
  push:
    branches:
      - main

jobs:
  install-kubectl:
    runs-on: ubuntu-latest
    name: Install Kubectl for OKE
    env:
      OCI_CLI_USER: ${{ secrets.OCI_CLI_USER }}
      OCI_CLI_TENANCY: ${{ secrets.OCI_CLI_TENANCY }}
      OCI_CLI_FINGERPRINT: ${{ secrets.OCI_CLI_FINGERPRINT }}
      OCI_CLI_KEY_CONTENT: ${{ secrets.OCI_CLI_KEY_CONTENT }}
      OCI_CLI_REGION: ${{ secrets.OCI_CLI_REGION }}

    steps:
      - name: Check OCI CLI installation
        run: |  
          if ! command -v oci &> /dev/null; then
            echo "OCI CLI not found, installing..."
            # Continue with the installation steps
            curl -L -O https://raw.githubusercontent.com/oracle/oci-cli/master/scripts/install/install.sh
            chmod +x install.sh
            ./install.sh --accept-all-defaults
            mv ~/bin/oci /usr/local/bin
            oci --version 
          else
            echo "OCI CLI already installed"
          fi

      - name: Configure OKE Cluster
        run: |
          oci ce cluster create-kubeconfig --cluster-id ${{ vars.OKE_CLUSTER_OCID }} --file $HOME/.kube/config --region ${{ secrets.OCI_CLI_REGION }} --token-version 2.0.0          
          sed -i "s|${{ env.oke_private_ip }}|127.0.0.1|g" $HOME/.kube/config
          sleep 5
          kubectl cluster-info
          if [ $? == 0 ]
          then
            echo "---------------------------------------------------------------"
            echo "Successfully Connected to your Private OKE Cluster"
            echo "---------------------------------------------------------------"
          else
            echo "---------------------------------------------------------------"
            echo "Unable to Authenticate with Private OKE Cluster"
            echo "---------------------------------------------------------------"
          fi
          
      # - name: Configure Kubectl
      #   uses: oracle-actions/configure-kubectl-oke@v1.3.2
      #   id: test-configure-kubectl-oke-action
      #   with:
      #     cluster: ${{ secrets.OKE_CLUSTER_OCID }}

      - name: Run Kubectl
        run: kubectl get nodes -A
